  [31morigin/01-Development_Environment_Setup_Cuyangan[m
  [31morigin/01_Development_Environment_Setup_Abinon[m
  [31morigin/01_Development_Environment_Setup_AldrinJay[m
  [31morigin/01_Development_Environment_Setup_Andaya[m
  [31morigin/01_Development_Environment_Setup_Aquisan[m
  [31morigin/01_Development_Environment_Setup_Balansi[m
  [31morigin/01_Development_Environment_Setup_Bandao[m
  [31morigin/01_Development_Environment_Setup_Bangonan[m
  [31morigin/01_Development_Environment_Setup_Calderon[m
  [31morigin/01_Development_Environment_Setup_Catayao[m
  [31morigin/01_Development_Environment_Setup_Damugo[m
  [31morigin/01_Development_Environment_Setup_Godoy[m
  [31morigin/01_Development_Environment_Setup_Gullunan[m
  [31morigin/01_Development_Environment_Setup_Ho[m
  [31morigin/01_Development_Environment_Setup_ICAD[m
  [31morigin/01_Development_Environment_Setup_Rosalejos[m
  [31morigin/01_Development_Environment_Setup_Sarino[m
  [31morigin/01_Development_Environment_Setup_Sigue[m
  [31morigin/01_Development_Environment_Setup_Visaya[m
  [31morigin/01_End_Development_Environment_Setup[m
  [31morigin/01_Environment_Setup_Hunas[m
  [31morigin/01_Start_Development_Environment_Setup[m
  [31morigin/02_End_First_App[m
  [31morigin/02_First_App_Andaya[m
  [31morigin/02_First_App_Balansi[m
  [31morigin/02_First_App_Bangonan[m
  [31morigin/02_First_App_Calderon[m
  [31morigin/02_First_App_Catayao[m
  [31morigin/02_First_App_Cuyangan[m
  [31morigin/02_First_App_Damugo[m
  [31morigin/02_First_App_Godoy[m
  [31morigin/02_First_App_Gullunan[m
  [31morigin/02_First_App_Sarino[m
  [31morigin/02_First_App_Sigue[m
  [31morigin/02_First_App_Visaya[m
  [31morigin/02_Start_First_App[m
  [31morigin/03[m
  [31morigin/03-Start_Project_Tracker_Lang-odan[m
  [31morigin/03_End_Project_Tracker[m
  [31morigin/03_Project_Tracker_Acosta[m
  [31morigin/03_Project_Tracker_AldrinJay[m
  [31morigin/03_Project_Tracker_Bala-oy[m
  [31morigin/03_Project_Tracker_Balansi[m
  [31morigin/03_Project_Tracker_Bangonan[m
  [31morigin/03_Project_Tracker_Calderon[m
  [31morigin/03_Project_Tracker_Catayao[m
  [31morigin/03_Project_Tracker_Gullunan[m
  [31morigin/03_Project_Tracker_LARON[m
  [31morigin/03_Project_Tracker_Sigue[m
  [31morigin/03_Project_Tracker_Visaya[m
  [31morigin/03_Start_Project_Tracker[m
  [31morigin/04_End_Student_Article_Publication_Platform[m
  [31morigin/04_Start_Student_Article_Publication_Platform[m
  [31morigin/04_Student-Article_Publication_Platform_Group3[m
  [31morigin/04_Student_Article_Platform_group1[m
  [31morigin/04_Student_Article_Publication_Group_5[m
  [31morigin/04_Student_Article_Publication_Platform_6[m
  [31morigin/04_Student_Article_Publication_Platform_Group_2[m
  [31morigin/04_Student_Article_Publication_Platform_Sigue[m
  [31morigin/05_End_My_First_Flutter_App[m
  [31morigin/05_My_First_Flutter_App_Abinon[m
  [31morigin/05_My_First_Flutter_App_Acosta[m
  [31morigin/05_My_First_Flutter_App_Andaya[m
  [31morigin/05_My_First_Flutter_App_Bangonan[m
  [31morigin/05_My_First_Flutter_App_Calderon[m
  [31morigin/05_My_First_Flutter_App_Catayao[m
  [31morigin/05_My_First_Flutter_App_Cirilo[m
  [31morigin/05_My_First_Flutter_App_Cuyangan[m
  [31morigin/05_My_First_Flutter_App_Damugo[m
  [31morigin/05_My_First_Flutter_App_Godoy[m
  [31morigin/05_My_First_Flutter_App_Gullunan[m
  [31morigin/05_My_First_Flutter_App_RosalejosSean[m
  [31morigin/05_My_First_Flutter_App_Sarino[m
  [31morigin/05_My_First_Flutter_App_Visaya[m
  [31morigin/05_My_First_Flutter_Icad[m
  [31morigin/05_Start_My_First_Flutter_App[m
  [31morigin/HEAD[m -> origin/main
  [31morigin/main[m
  [31morigin/wmad-306-2-pr[m
